config/routes.rb
Clorg::Application.routes.draw do

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  resources :events
  resources :tags

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar/week/(:year(/:weeknumber))' => 'calendar#show', :as => :week_calendar, :constraints => {:year => /\d{4}/, :weeknumber => /\d{1,2}/}

  
  resources :messages do
    resources :comments
  end

  match '/messages', :to => 'messages#index'
  match '/messages/tag/:tag', :to => 'messages#index', :as => :messages_tagged_by

  resources :users do
    member do
      get :activate
    end
  end

  resources :password_resets
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'

  match '/img/:name', :to => redirect('/assets/%{name}.png')

  root :to => 'pages#home'

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :user_id, :tag_list
  acts_as_taggable

  default_scope :order => 'created_at DESC'

  has_many :comments
  belongs_to :user, :foreign_key => :user_id

  validates :content, :user_id, :presence => true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :get_message, :only => [:show, :edit, :destroy, :update]
  before_filter :new_message, :only => [:index, :new]

  def index
    @tags = Tag.all
    @activeTag = params[:tag]
    if params[:tag]
      @messages = Message.tagged_with(@activeTag).page(params[:page]).per_page(10).includes(:comments, :user)
    else
      @messages = Message.page(params[:page]).per_page(10).includes(:comments, :user)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.js #show.js.erb
    end
  end

  def show
    @comments = @message.comments
  end

  def new
  end

  def edit
  end

  def create
    @message = Message.new(params[:message])
    @message.user_id = current_user.id
    if @message.save
      redirect_to @message, notice: 'Message was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    if @message.update_attributes(params[:message])
      redirect_to @message, notice: 'Message was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @message.destroy
    redirect_to messages_url
  end

  def new_message
    @message = Message.new
  end

  def get_message
    @message = Message.find(params[:id])
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
	def comments_for(message)
		message.comments
	end
end

app/views/messages/_form.html.haml
= simple_form_for(@message) do |f|
  = f.input :content, :wrapper => :prepend, :label => false do
    %span.add-on
      <i class="icon-file"></i>
    = f.input_field :content, :placeholder => "Nachricht"
    = f.hidden_field :tag_list
  .actions
    = f.submit

app/views/messages/_message.html.haml
= div_for(message, class: "well messagebox") do
  .metainfo.row-fluid
    %p.span9
      = message.user.username
      = message.created_at.strftime("%H:%M %e.%m.%Y")
    - if can_delete?(message)
      #control.span3
        .btn-group.pull-right
          = link_to 'Edit', edit_message_path(message), class: "btn btn-primary"
          = link_to 'Destroy', message, confirm: 'Are you sure?', method: :delete, class: "btn btn-primary"
  .content
    %p
      = message.content

  .comments.well.commentsbox
    - comments_for(message).each do |comment|
      = render 'comments/comment', comment: comment, message: message
    = link_to 'Write Comment', new_message_comment_path(message)
  
  %br

app/views/messages/edit.html.haml
%h1 Editing message
= render 'form'
= link_to 'Show', @message
|
\#{link_to 'Back', messages_path}

app/views/messages/filtered_index.js.erb
$('#message_tag_id').val("<%= @tag.id %> ");
$('.radio .tag').removeClass('active');
$('#<%= dom_id(@tag) %>').addClass('active');
$('#messages .message').slideUp('slow').remove();
$('#messages').append("<%= escape_javascript(render @messages) %>").hide().slideDown('slow');

app/views/messages/index.html.haml
%h1 Latest Messages
%br
.row-fluid
  .span8
    #messages
      = render @messages
      = will_paginate @messages, previous_label: h("<"), next_label: h(">"), inner_window: 1, outer_window: 0
  .span1
  .span3
    = render 'layouts/tagbar'
    %br
    %h3 Write a Message
    = render 'form'

app/views/messages/index.js.erb
$('#messages').append('<%= j render(@messages) %>');
<% if @messages.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@messages) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/messages/new.html.haml
%h1 New message
= render 'form'
= link_to 'Back', messages_path

app/views/messages/show.html.haml
%p#notice= notice
%p
  %b User:
  = @message.user.username
  ,
  \#{@message.user.id}
  %b Content:
  = @message.content
  Show #{link_to pluralize(@message.comments.size, ' Comments'), message_comments_path(@message)}
  \#{link_to 'write Comment', new_message_comment_path(@message)}
.comments
  = render @comments, message: @message
= link_to 'Edit', edit_message_path(@message)
|
\#{link_to 'Back', messages_path}