config/routes.rb
Clorg::Application.routes.draw do

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  resources :events
  resources :tags

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar/week/(:year(/:weeknumber))' => 'calendar#show', :as => :week_calendar, :constraints => {:year => /\d{4}/, :weeknumber => /\d{1,2}/}

  
  resources :messages do
    resources :comments
  end

  match '/messages', :to => 'messages#index'
  match '/messages/tag/:tag', :to => 'messages#index', :as => :messages_tagged_by

  resources :users do
    member do
      get :activate
    end
  end

  resources :password_resets
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'

  match '/img/:name', :to => redirect('/assets/%{name}.png')

  root :to => 'pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id, :message_id
  belongs_to :user, :foreign_key => :user_id
  belongs_to :message, :foreign_key => :message_id


  validates :content, :presence => true
  validates :user_id, :presence => true
  validates :message_id, :presence => true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :get_message
  before_filter :get_comment, :only => [:show, :edit, :destroy, :update]
  before_filter :new_comment, :only => [:index, :new]

  def index
    @comments = @message.comments
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @comment = Comment.new(params[:comment])
    @comment.user_id = current_user.id
    @comment.message_id = @message.id
    if @comment.save
      redirect_to @message, notice: 'Comment was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @comment.user_id = current_user.id
    if @comment.update_attributes(params[:comment])
      redirect_to [@message, @comment], notice: 'Comment was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @comment.destroy
    redirect_to @message
  end

  def get_message
    @message = Message.find(params[:message_id])
  end

  def get_comment
    @comment = @message.comments.find(params[:id])
  end

  def new_comment
    @comment = Comment.new
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.comment-metainfo.row-fluid
  .user.span9
    User_ID:
    = comment.user_id # should be .user soon...
  .controll.span3
    .btn-group.pull-right
      - if can_delete?(comment)
        = link_to 'Edit', edit_message_comment_path(message, comment), :class => "btn btn-mini btn-primary"
        = link_to 'Destroy', [message, comment], :method => :delete, :confirm => "Are you sure?", :class => "btn btn-mini btn-primary"
.content
  %p
    = comment.content

app/views/comments/_form.html.haml
= simple_form_for([@message, @comment]) do |f|
  = render 'shared/flash_alert'
  = f.input :content, :wrapper => :prepend, :label => false do
    %span.add-on
      <i class="icon-comment"></i>
    = f.input_field :content, :placeholder => "Kommentar"
  .actions
    = f.submit

app/views/comments/edit.html.haml
%h1 Editing comment
= render 'form'
= link_to 'Show', [@message, @comment]
|
\#{link_to 'Back', message_comments_path(@message)}

app/views/comments/index.html.haml
Comments of this Message:
- @comments.each do |comment|
  %ul
    = comment.content
  = link_to 'Edit', edit_message_comment_path(@message, comment)
  = link_to 'Destroy', [@message, comment], confirm: 'Are you sure?', method: :delete

app/views/comments/new.html.haml
%h1 New comment
= render 'form'

app/views/comments/show.html.haml
%p#notice= notice
%p
  %b Content:
  = @comment.content
= link_to 'Edit', edit_message_comment_path(@message, @comment)
= link_to 'Destroy', [@message, @comment], :method => :delete, :confirm => "Are you sure?"
= link_to 'Back', message_path(@message)