config/routes.rb
Clorg::Application.routes.draw do

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  resources :events
  resources :tags

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar/week/(:year(/:weeknumber))' => 'calendar#show', :as => :week_calendar, :constraints => {:year => /\d{4}/, :weeknumber => /\d{1,2}/}

  
  resources :messages do
    resources :comments
  end

  match '/messages', :to => 'messages#index'
  match '/messages/tag/:tag', :to => 'messages#index', :as => :messages_tagged_by

  resources :users do
    member do
      get :activate
    end
  end

  resources :password_resets
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'

  match '/img/:name', :to => redirect('/assets/%{name}.png')

  root :to => 'pages#home'

end

app/views/layouts/_navigation_right.html.haml
/ NAVIGATION RIGHT
.span2.sidebar-nav
  %ul.nav.nav-list.nav-pills.nav-stacked
    %li.nav-header Navigation
    <li
    - if controller.controller_name == "pages"
      class="active"
    >
    %a{:href => root_path}
      %i.icon-home
      Home
    <li
    - if controller.controller_name == "messages"
      class="active"
    >
    %a{:href => messages_path}
      %i.icon-envelope
      Messages
    <li
    - if controller.controller_name == "calendar"
      class="active"
    >
    %a{:href => calendar_path}
      %i.icon-book
      Calendar
    <li
    - if controller.controller_name == "users" && controller.action_name == "edit"
      class="active"
    >
    %a{:href => edit_user_path(current_user)}
      %i.icon-cog
      Settings
/ END NAVIGATION

app/views/layouts/_navigation_top.html.haml
/ NAVIGATIONBAR-TOP
.navbar.navb.ar-fixed-top
  .navbar-inner
    .container
      %a.brand{:href => "/"}
        Clorg
        / <haml:loud>@title</haml:loud>
      / <haml:loud>  controller.action_name </haml:loud>
      %ul.nav
        = ca_li_link_to "Start", root_path
        = ca_li_link_to "About", about_path
        = ca_li_link_to "Contact", contact_path
        - if logged_in?
          <li
          - if controller.controller_name == "sessions"
            class="active"
          >
          \#{link_to "Sign out", logout_path, :html_options => {:method => :delete}}
        - else
          <li
          - if controller.controller_name == "sessions"
            class="active"
          >
          \#{link_to "Sign in", login_path}
          <li
          - if (controller.controller_name == "users") && (controller.action_name == "new")
            class="active"
          >
          \#{link_to "Sign up", signup_path}
      .nav-collapse
        %form.navbar-search.pull-right
          %input.search-query{:placeholder => "Search", :type => "text"}
/ END NAVIGATIONBAR

app/views/layouts/_tagbar.html.haml
//FIXME: Use Helper
-if @activeTag.nil?
  =hidden_field_tag 'activeTag', 'All'
-else
  =hidden_field_tag 'activeTag', @activeTag

- unless @tags.nil?
  .btn-group.radio
    - if controller.controller_name == "messages"
      #All.tag.btn.btn-primary
        = link_to "All", messages_path
      - @tags.each do |t|
        .btn{:id => "#{t.name}", class: "btn-primary"}
          = link_to t.name, messages_tagged_by_path(t.name)

    - if controller.controller_name == "calendar" && controller.action_name == "index"
      #All.tag.btn.btn-primary
        = link_to "All", calendar_path
      - @tags.each do |t|
        .btn{:id => "#{t.name}", class: "btn-primary"}
          = link_to t.name, calendar_path(:tag => t.name)

    - if controller.controller_name == "calendar" && controller.action_name == "show"
      #All.tag.btn.btn-primary
        = link_to "All", week_calendar_path
      - @tags.each do |t|
        .btn{:id => "#{t.name}", class: "btn-primary"}
          = link_to t.name, week_calendar_path(:tag => t.name)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Clorg | #{@title || "The Club Organizer"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %section.round
      / flash alert
      .container-fluid
        = render 'layouts/navigation_top' 
        .row-fluid
          / CONTENT
          .span10.well
            = yield
          / END CONTENT
          - if logged_in?
            = render 'layouts/navigation_right'
        / 
        / FOOTER
        .row-fluid.navbar-fixed-bottom
          .pull-right{:style => "padding-right:20px;"}
            = link_to "About", about_path
            = link_to "Contact", contact_path
            \&copy Clorg 2012
        / END FOOTER